[app]
name = "iobscan-open-api"
addr = "0.0.0.0:8000"
version = "0.1"
env = "dev"
start_task = false
start_monitor = false
api_cache_alive_seconds = 3
max_page_size = 3000
prometheus_port = "9090"
enable_signature = false
enable_rate_limit = false
rate_limit_policy = "100/60" ## m/n  m: frequency; n: cycle time(unit: s)

[log]
log_level = "debug"
log_file_name = "sw"
log_path = "/var/log"
log_max_age_day = 15
log_rotation_time_day = 1
log_output = "std"

[mongo]
# Replace with your actual MongoDB connection string
url = "mongodb://username:password@host:port/?connect=direct&authSource=database_name"
database = "your_database_name"

[redis]
# Replace with your actual Redis configuration
addrs = "your_redis_host:6379"
user = ""
password = "your_redis_password"
mode = "single"
db = 0

[spi]
coingecko_price_url = "https://api.coingecko.com/api/v3/simple/price"

[task]
ibc_tx_fail_log_task = "0 0 2 * * ?"
ibc_chain_fee_statistic_task = "0 */5 * * * ?"
ibc_address_statistic_task = "0 */5 * * * ?"
ibc_cache_denom_symbol_task = "0 */3 * * * ?"
